.lint_common:
  stage: test
  cache:
    key: ${CI_COMMIT_REF_SLUG}-node-modules
    paths:
      - node_modules
    policy: pull
  script:
    - npm run lint

# ---

image: registry.gitlab.lstv.io/common/ci/frontend:14.17.4-${LSTV_DOCKER_IMAGE_VERSION}

default:
  tags: ["docker-exec"]

variables:
  CI_BROWSER_APP_CHART: browser-app
  CI_BROWSER_APP_IMAGE: $CI_REGISTRY_IMAGE/browser-app

stages:
  # default stages
  - pre_test
  - test
  - build
  - deploy

test:install:
  stage: pre_test
  cache:
    key: ${CI_COMMIT_REF_SLUG}-node-modules
    paths:
      - node_modules
      - cypress_bin
  script:
    - npm ci
  only:
    refs:
      - master
      - merge_requests

test:lint:
  extends: .lint_common
  only:
    refs:
      - master
      - merge_requests

test:lint_man:
  extends: .lint_common
  when: manual

build:
  stage: build
  image: registry.gitlab.lstv.io/common/ci/docker:20.10
  script:
    - imageTag=$CI_COMMIT_TAG
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build
      --build-arg graphql_api_url="$LSTV_GRAPHQL_API_URL"
      --build-arg locales_api_key="$LSTV_LOCALISE_API_KEY"
      --build-arg LSTV_DOCKER_IMAGE_VERSION="$LSTV_DOCKER_IMAGE_VERSION"
      -t $CI_BROWSER_APP_IMAGE:$imageTag
      -t $CI_BROWSER_APP_IMAGE:latest
      .
    - docker push $CI_BROWSER_APP_IMAGE:$imageTag
    - docker push $CI_BROWSER_APP_IMAGE:latest
  only:
    - tags
