import React from 'react';
import type { NextPage } from 'next';
import Head from 'next/head';
import { LeftSideHomePage, RightSideHomePage } from '@/components/Sections/HomeSection';
import TechnologySection from '@/components/Sections/TechnologySection';
import ContactSection from '@/components/Sections/ContactSection';

const Home: NextPage = (): React.ReactElement => (
  <>
    <Head>
      <title>Michael Kubín</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.png" />
    </Head>
    <section className="flex h-screen pb-20">
      <LeftSideHomePage />
      <RightSideHomePage />
    </section>
    <section className="flex h-screen pb-20 bg-green">
      <TechnologySection />
    </section>
    <section className="flex h-screen pb-20 bg-purple">
      <ContactSection />
    </section>
  </>
);
export default Home;
