import React from 'react';
import type { NextPage } from 'next';
import Head from 'next/head';
import Link from 'next/link';
import { useRouter } from 'next/router';

const navigationConfig = [
  { name: 'Technology', url: '/#technology' },
  { name: 'Contact', url: '/#contact' },
];

const experiences = [
  {
    companyName: 'Company Name', date: 'from: 23.1 to: 15.2', where: 'where: Czech', jobdesc: 'Job description', desc: 'n publishing and graphic design, lorem ipsum is common placeholder text used to demonstrate the graphic elements of a document or visual presentation, such',
  },
  {
    companyName: 'Company Name', date: 'from: 23.1 to: 15.2', where: 'where: Czech', jobdesc: 'Job description', desc: 'n publishing and graphic design, lorem ipsum is common placeholder text used to demonstrate the graphic elements of a document or visual presentation, such',
  },
  {
    companyName: 'Company Name', date: 'from: 23.1 to: 15.2', where: 'where: Czech', jobdesc: 'Job description', desc: 'n publishing and graphic design, lorem ipsum is common placeholder text used to demonstrate the graphic elements of a document or visual presentation, such',
  },
  {
    companyName: 'Company Name', date: 'from: 23.1 to: 15.2', where: 'where: Czech', jobdesc: 'Job description', desc: 'n publishing and graphic design, lorem ipsum is common placeholder text used to demonstrate the graphic elements of a document or visual presentation, such',
  },
];

const Home: NextPage = (): React.ReactElement => {
  const router = useRouter();

  return (
    <>
      <Head>
        <title>Michael Kubín</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.png" />
      </Head>
      <section id="home" className="flex h-screen pb-20">
        {
        /**
         * Section Programmer
         */
      }
        <div className="flex flex-col flex-1 pl-24">
          <div className="flex flex-col justify-center flex-1">
            <h1 className="pt-5 pb-10 text-6xl font-Asap">Michael Kubín</h1>
            <p className="text-3xl italic font-AsapItal">Frontend developer</p>
          </div>
          {
        /**
         * Section Navigation
         */
        }
          <div className="flex flex-row">
            {
            navigationConfig.map((nav) => (
              <Link href={nav.url} key={nav.url} scroll={false} replace passHref>
                <div className="mr-10 w-[200px] h-[50px]">
                  <button type="button" className="bg-transparent border rounded-full cursor-pointer text-sky500 w-[100%] h-[100%] hover:w-[110%]">
                    {nav.name}
                  </button>
                </div>
              </Link>
            ))
          }
          </div>
        </div>
        {
        /**
         * Section Timeline
         */
        }
        <div className="flex flex-col justify-start flex-1 pt-24">
          <h1 className="mx-auto mb-10 text-3xl font-AsapItal">Work experience</h1>
          <div className="flex flex-col w-4/5 h-full mx-auto overflow-auto">
            {
              experiences.map((experience) => (
                <section key={experience.companyName} className="flex h-48 mb-10 border border-solid shadow-lg border-sky500/5 rounded-2xl shadow-sky500/5 hover:bg-sky500/5">
                  <div className="flex w-full cursor-pointer p-7">
                    <div className="w-[60px] h-[60px] bg-yellow" />
                    <div className="flex flex-col ml-10">
                      <h1 className="pb-1 text-lg font-AsapItal">{experience.companyName}</h1>
                      <p className="text-sm italic font-Asap">{experience.date}</p>
                      <p className="text-sm italic font-Asap">{experience.where}</p>
                      <h1 className="pt-5 text-lg font-AsapItal">{experience.jobdesc}</h1>
                      <div className="w-96">
                        <p className="text-base truncate">{experience.desc}</p>
                      </div>
                    </div>
                  </div>
                </section>
              ))
            }
          </div>
        </div>
      </section>
      <section id="technology" className="h-screen bg-green" />
      <section id="contact" className="h-screen bg-purple" />
    </>
  );
};

export default Home;
