import React from 'react';
import type { NextPage } from 'next';
import Head from 'next/head';
import HomeSection from '@/components/Sections/HomeSection';
import ContactSection from '@/components/Sections/ContactSection';
import MotionDiv from '@/components/Motions/MotionDiv';

const Home: NextPage = (): React.ReactElement => (
  <>
    <Head>
      <title>Michael Kubín</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.png" />
    </Head>
    <section className="main-page-layout">
      <MotionDiv>
        <HomeSection />
      </MotionDiv>
    </section>
    <section className="main-page-layout">
      <ContactSection />
    </section>
  </>
);

export default Home;
