import React from 'react';
import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import CenterLayout from 'layouts/CenterLayout';

const Home: NextPage = (): React.ReactElement => (
  <>
    <Head>
      <title>Michael Kubín</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.png" />
    </Head>
    <section id="michael-kubin" className="pt-28 h-[100vh]">
      <CenterLayout>
        <h1 className="mx-auto pb-7">Hi and welcome to my world.</h1>
        <div className="flex flex-row justify-between flex-1">
          <div className="flex flex-col justify-center w-[321px]">
            <h1 className="pb-10 mx-auto">About me.</h1>
            <p>I would like to introduce myself. I am fronted developer with a passion for technology and sports.</p>
            <Image src="/image/me_mack.png" height={321} width={321} className="bg-pink" />
          </div>
          <div className="flex flex-col  w-[321px]" />
        </div>
      </CenterLayout>
    </section>
    <section id="technology" className="h-[100vh] w-[100%] bg-green" />
    <section id="contact" className="h-[100vh] bg-purple" />
  </>
);

export default Home;
