name: Next.js Pipelines

on: [push]

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest

    stratefgy: 
      matrix:
        node-version: [14.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: | 
          echo "Running Installing Dependecies ... "
          npm install

      - name: Run Linting
        run: |
          echo "Running Linting ... "
          npm run lint

  build:
    name: build
    runs-on: ubuntu-laatest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: | 
          echo "Running Installing Dependecies ... "
          npm install

      - name: Run build
        run: |
          echo "Build app ... "
          npm run build
